name: Deploy Static Website

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/deploy-web.yml'

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload /web to Azure Blob Storage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source './web' \
              --overwrite \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}
